### ISSUE TITLE
==6132==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD

### ISSUE THREAD

**Issue by Idriel** [canokeys/canokey-core#113]
Hi, 
I am trying to test it using pcscd and Smart Card Virtual Reader but it says following error. 

```
00000001 [126012534969664] readerfactory.c:554:RFAddReader() Using the pcscd polling thread
00000020 [126012534969664] readerfactory.c:1094:RFInitializeReader() Attempting startup of Canokey [OpenPGP PIV OATH] 00 00 using /usr/local/lib/libu2f-virt-card.so
==6132==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```

It was compiled like
```
cmake -S . -B build \
        -DENABLE_TESTS=ON \
        -DVIRTCARD=ON \
        -DENABLE_DEBUG_OUTPUT=ON \
        -DCMAKE_BUILD_TYPE=Debug \
    && cmake --build build --verbose --parallel
```

```
 ldd /usr/local/lib/libu2f-virt-card.so 
	linux-vdso.so.1 (0x00007ffe68fb0000)
	libasan.so.8 => /lib/x86_64-linux-gnu/libasan.so.8 (0x00007f638c000000)
	libpcsclite.so.1 => /lib/x86_64-linux-gnu/libpcsclite.so.1 (0x00007f638c7e3000)
	libubsan.so.1 => /lib/x86_64-linux-gnu/libubsan.so.1 (0x00007f638b800000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f638b400000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f638c6fa000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f638bfd2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f638d170000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f638b000000)
```

bash -c 'LD_PRELOAD="$(gcc -print-file-name=libasan.so) $(gcc -print-file-name=libubsan.so)" pcscd -a -f >/tmp/pcscd.log &'
```
==6237==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x777a52cf74e8 in strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:578
    #1 0x567836beb12c  (/usr/sbin/pcscd+0x1512c) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #2 0x567836bddf76  (/usr/sbin/pcscd+0x7f76) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #3 0x567836be367f  (/usr/sbin/pcscd+0xd67f) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #4 0x567836be380e  (/usr/sbin/pcscd+0xd80e) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #5 0x567836bdb59a  (/usr/sbin/pcscd+0x559a) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #6 0x777a5202a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #7 0x777a5202a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #8 0x567836bdbb84 in _start (/usr/sbin/pcscd+0x5b84) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)

SUMMARY: AddressSanitizer: 7 byte(s) leaked in 1 allocation(s).

```

**Comment by z4yx** [comment]
The following command should work:
`sudo LD_PRELOAD="$(gcc -print-file-name=libasan.so) $(gcc -print-file-name=libubsan.so)" pcscd -af`

Memory leaking is detected when pcscd exits. It should be some bug inside pcscd instead of Canokey, because canokey-core doesn't allocate memory on heap.

**Comment by Idriel** [comment]
Thank you for fast response. 

It's working. 

```
#pcsc_scan
Using reader plug'n play mechanism
Scanning present readers...
0: ...
1: ...
2: Canokey [OpenPGP PIV OATH] 00 00


 Reader 2: Canokey [OpenPGP PIV OATH] 00 00
  Event number: 0
  Card state: Card inserted, 
  ATR: 3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99

ATR: 3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99
+ TS = 3B --> Direct Convention
+ T0 = F7, Y(1): 1111, K: 7 (historical bytes)
  TA(1) = 11 --> Fi=372, Di=1, 372 cycles/ETU
    10752 bits/s at 4 MHz, fMax for Fi = 5 MHz => 13440 bits/s
  TB(1) = 00 --> VPP is not electrically connected
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 65 --> Block Waiting Integer: 6 - Character Waiting Integer: 5
+ Historical bytes: 43 61 6E 6F 6B 65 79
  Category indicator byte: 43 (proprietary format)
+ TCK = 99 (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99
	Canokey (Other)
	http://canokeys.org/

```
