### ISSUE TITLE
Failed to connect to yubikey: PCSC service not available.

### ISSUE THREAD

**Issue by Idriel** [canokeys/canokey-core#115]
Trying to create PIV with yubico-piv-tool 2.7.0

```
yubico-piv-tool -r canokey -a generate -s 9a -A RSA2048 -o public-key.pem
Failed to connect to yubikey: PCSC service not available.
Try restarting the PCSC subsystem.
```

pcsc debug log that it's running
```
00000146 [140373098293696] readerfactory.c:1094:RFInitializeReader() Attempting startup of Canokey [OpenPGP PIV OATH] 00 00 using /usr/local/lib/libu2f-virt-card.so
00002749 [140373098293696] dyn_unix.c:105:DYN_GetAddress() IFDHCreateChannelByName: /usr/local/lib/libu2f-virt-card.so: undefined symbol: IFDHCreateChannelByName
00000051 [140373098293696] readerfactory.c:936:RFBindFunctions() Loading IFD Handler 2.0
IFDHCreateChannel 0 0
IFDHGetCapabilities 0 0xfb3
00000173 [140373098293696] readerfactory.c:394:RFAddReader() Using the reader polling thread
IFDHGetCapabilities 0 0xfae
00000129 [140373098293696] pcscdaemon.c:671:main() pcsc-lite 2.0.3 daemon ready.
IFDHPowerICC 0 Action=0x1f4
00000187 [140372959299264] eventhandler.c:289:EHStatusHandlerThread() powerState: POWER_STATE_POWERED
00000009 [140372959299264] Card ATR: 3B F7 11 00 00 81 31 FE 65 43 61 6E 6F 6B 65 79 99 
00000059 [140373098293696] pcscdaemon.c:754:main() Using drivers directory: /usr/lib/pcsc/drivers
00003475 [140373098293696] hotplug_libudev.c:298:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0001, path: /dev/bus/usb/001/001
00000147 [140373098293696] hotplug_libudev.c:298:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0001, path: /dev/bus/usb/001/001
00000167 [140373098293696] hotplug_libudev.c:298:get_driver() Looking for a driver for VID: 0x80EE, PID: 0x0021, path: /dev/bus/usb/001/002
00000222 [140373098293696] hotplug_libudev.c:298:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/002/001
```

When executing yubico-piv-tool I got error

```
00000007 [129814518302400] APDU: 00 A4 04 00 05 A0 00 00 03 08 00 
IFDHTransmitToICC 0 T=1
[DBG] PC_to_RDR_XfrBlock(180): O: 00A4040005A00000030800
[DBG] process_apdu(200): applet switched to: 1
[DBG] PC_to_RDR_XfrBlock(199): I: 61114F0600001000010079074F05A0000003089000
00000195 [129814518302400] SW: 61 11 4F 06 00 00 10 00 01 00 79 07 4F 05 A0 00 00 03 08 90 00 
00000006 [129814518302400] winscard.c:1650:SCardTransmit() UnrefReader() count was: 2
00000006 [129814518302400] winscard_svc.c:719:ContextThread() TRANSMIT for client 9, rv=SCARD_S_SUCCESS
00000030 [129814518302400] winscard_svc.c:381:ContextThread() Received command: TRANSMIT from client 9
00000029 [129814518302400] readerfactory.c:862:RFReaderInfoById() RefReader() count was: 1
00000021 [129814518302400] winscard.c:1597:SCardTransmit() Send Protocol: T=1
00000008 [129814518302400] APDU: 00 20 00 80 00 
IFDHTransmitToICC 0 T=1
[DBG] PC_to_RDR_XfrBlock(180): O: 0020008000
/home/canokey-core/littlefs/lfs.c:49:28: runtime error: member access within null pointer of type 'const struct lfs_config'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11702==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x7610d01cbb80 bp 0x7610cc3defe0 sp 0x7610cc3def60 T6)
==11702==The signal is caused by a READ memory access.
==11702==Hint: address points to the zero page.
    #0 0x7610d01cbb80 in lfs_bd_read /home/canokey-core/littlefs/lfs.c:49
    #1 0x7610d01e024e in lfs_dir_fetchmatch /home/canokey-core/littlefs/lfs.c:1091
    #2 0x7610d01e7274 in lfs_dir_find /home/canokey-core/littlefs/lfs.c:1516
    #3 0x7610d01ff9e3 in lfs_file_rawopencfg /home/canokey-core/littlefs/lfs.c:3031
    #4 0x7610d0225be5 in lfs_file_opencfg /home/canokey-core/littlefs/lfs.c:5953
    #5 0x7610d018e399 in get_file_size /home/canokey-core/src/fs.c:106
    #6 0x7610d019d157 in pin_get_size /home/canokey-core/src/pin.c:73
    #7 0x7610d019d221 in pin_get_retries /home/canokey-core/src/pin.c:76
    #8 0x7610d0154a9d in piv_verify /home/canokey-core/applets/piv/piv.c:470
    #9 0x7610d016cd94 in piv_process_apdu /home/canokey-core/applets/piv/piv.c:1172
    #10 0x7610d018a2e0 in process_apdu /home/canokey-core/src/apdu.c:218
    #11 0x7610d016eb4a in PC_to_RDR_XfrBlock /home/canokey-core/interfaces/USB/class/ccid/ccid.c:192
    #12 0x7610d00d394b in IFDHTransmitToICC /home/canokey-core/virt-card/ifdhandler.c:139
    #13 0x5db60db774bf  (/usr/sbin/pcscd+0x134bf) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #14 0x7610d825ea41 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #15 0x7610d769ca93 in start_thread nptl/pthread_create.c:447
    #16 0x7610d7729c3b in clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/canokey-core/littlefs/lfs.c:49 in lfs_bd_read
Thread T6 created by T0 here:
    #0 0x7610d82f51f9 in pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x5db60db6b705  (/usr/sbin/pcscd+0x7705) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #2 0x5db60db68d57  (/usr/sbin/pcscd+0x4d57) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)
    #3 0x7610d762a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #4 0x7610d762a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #5 0x5db60db69b84 in _start (/usr/sbin/pcscd+0x5b84) (BuildId: b27663fdcfd07ab3c86b57c6ee88df91e4c13d7f)

==11702==ABORTING
```

**Comment by Idriel** [comment]
After reboot everything seems to start working normaly
